export const headers = {
    "id": 'ID',
    "firstName": 'First Name',
    "lastName": 'Last Name',
    "maidenName": 'Maiden Name',
    "age": 'Age',
    "gender": 'Gender',
    "email": 'Email',
    "phone": 'Phone',
    "username": 'User Name',
    "birthDate": 'Birth Date',
    "bloodGroup": 'Blood Group',
    "image": 'Image',
    "password": 'Password',
    "height": 'Height',
    "weight": 'Weight',
    "eyeColor": 'Eye Color',
    "hair": 'Hair',
    "domain": 'Domain',
    "ip": 'IP',
    "address": 'Address',
    "macAddress": 'MAC Address',
    "university": 'University',
    "bank": 'Bank',
    "company": ' Company',
    "ein": 'EIN',
    "ssn": 'SSN',
    "userAgent": 'User Agent',
    "title": 'Title',
    "description": "Description",
    "price": "Price",
    "discountPercentage": 'Discount',
    "rating": 'Rating',
    "stock": 'Stock',
    "brand": 'Brand',
    "category": 'Category',
    "thumbnail": 'Image'
}

export const categories = {
    "smartphones": 'Smart Phones',
    "laptops": "Laptops",
    "fragrances":"Fragrances" ,
    "skincare" : "Skin Care",
    "groceries": "Groceries",
    "home-decoration": "Home Decoration",
    "furniture": "Furniture",
    "tops": "Tops",
    "womens-dresses": "Women's Dresses",
    "womens-shoes": "Women's Shoes",
    "mens-shirts": "Men's Shirts",
    "mens-shoes": "Men's Shoes",
    "mens-watches": "Men's Watches",
    "womens-watches":"Women's Watches",
    "womens-bags":"Women's Bags",
    "womens-jewellery":"Women's Jewellery",
    "sunglasses": "Sunglasses",
    "automotive": "Automotive",
    "motorcycle": "Motorcycles",
    "lighting": "Lighting"

}